LR:
  penalty: ['l2']
  C: [0.01, 0.1, 1.0, 10.0]
  solver: ['liblinear', 'lbfgs']
  max_iter: [100, 200]

EN:
  alpha: [0.1, 1.0, 10.0]
  l1_ratio: [0.2, 0.5, 0.8]
  max_iter: [1000]
  tol: [0.0001, 0.001]

DT:
  max_depth: [None, 5, 10, 20]
  min_samples_split: [2, 5, 10]
  min_samples_leaf: [1, 2, 4]
  criterion: ['squared_error', 'friedman_mse']

RF:
  n_estimators: [100, 200]
  max_depth: [None, 10, 20]
  min_samples_split: [2, 5]
  min_samples_leaf: [1, 2]
  bootstrap: [True, False]

GB:
  n_estimators: [100, 200]
  learning_rate: [0.01, 0.1, 0.2]
  max_depth: [3, 5, 10]
  min_samples_split: [2, 5]
  min_samples_leaf: [1, 2]

SVR:
  kernel: ['rbf', 'linear']
  C: [0.1, 1.0, 10.0]
  epsilon: [0.1, 0.2, 0.5]
  gamma: ['scale', 'auto']
