apiVersion: apps/v1
kind: Deployment
metadata:
  name: preprocessing
spec:
  replicas: 2
  selector:
    matchLabels:
      app: preprocessing
  template:
    metadata:
      labels:
        app: preprocessing
    spec:
      containers:
        - name: preprocessing
          image: amanmlops/stock-price:v1
          ports:
            - containerPort: 8080
          command: ["python" ,"main.py"]


---
apiVersion: v1
kind: Service
metadata:
  name: airflow-service
spec:
  selector:
    app: preprocessing
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer

