apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow
spec:
  replicas: 2
  selector:
    matchLabels:
      app: airflow
  template:
    metadata:
      labels:
        app: airflow
    spec:
      containers:
        - name: airflow
          image: amanmlops/airflow:v1
          ports:
            - containerPort: 8080
          command: ["astro", "dev", "start"]
          envFrom:
            - secretRef:
                name: app-secrets

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: preprocess
spec:
  replicas: 2
  selector:
    matchLabels:
      app: preprocess
  template:
    metadata:
      labels:
        app: preprocess
    spec:
      containers:
        - name: preprocess
          image: amanmlops/stock-price:v3
          ports:
            - containerPort: 5050
          command: ["python", "app.py"]
          envFrom:
            - secretRef:
                name: app-secrets 

---
apiVersion: v1
kind: Service
metadata:
  name: airflow-service
spec:
  selector:
    app: airflow
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
  type: LoadBalancer


---
apiVersion: v1
kind: Service
metadata:
  name: preprocess-service
spec:
  selector:
    app: preprocess
  ports:
    - protocol: TCP
      port: 5051
      targetPort: 5050
  type: LoadBalancer


